import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { API_BASE_URL } from '../utils/api';

const CheckoutButton = ({ cartItems }) => {
  const { currentUser } = useAuth();
  const [isProcessing, setIsProcessing] = useState(false);

  const handleCheckout = async () => {
    // Basic frontend validations
    if (!cartItems || cartItems.length === 0) return;
    
    if (!currentUser) {
      console.warn("Authentication required: Please log in to proceed to checkout.");
      return;
    }

    setIsProcessing(true);

    try {
      // 1. Obtain the secure Firebase ID token directly from the AuthContext
      const token = await currentUser.getIdToken();

      // 2. Transmit the raw cart data to our highly secure backend
      const response = await fetch(`${API_BASE_URL}/api/checkout`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          // Pass the Bearer token for our requireAuth middleware
          'Authorization': `Bearer ${token}` 
        },
        body: JSON.stringify({ items: cartItems }),
      });

      const data = await response.json();

      // 3. Safely execute the redirect using the URL generated by Stripe
      if (data.url) {
        window.location.href = data.url;
      } else {
        console.error("Failed to initialize checkout session:", data.error);
      }
    } catch (error) {
      console.error("Network connection error during checkout:", error);
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <button
      onClick={handleCheckout}
      disabled={isProcessing || !cartItems || cartItems.length === 0}
      className="w-full flex items-center justify-center px-8 py-4 font-black tracking-widest uppercase border-2 border-current bg-inherit text-current hover:scale-[1.02] active:scale-95 transition-transform duration-200 disabled:opacity-40 disabled:pointer-events-none disabled:scale-100 cursor-pointer"
    >
      {isProcessing ? 'Processing...' : 'Secure Checkout'}
    </button>
  );
};

export default CheckoutButton;
